package com.jbk.hibernate;
// Generated 30 Apr, 2020 9:40:09 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.ColumnDefault;

/**
 * Addnewuser generated by hbm2java
 */
@Entity
@Table(name = "addnewuser", catalog = "mvcwithhibernate")
public class Addnewuser implements java.io.Serializable {

	private Integer id;
	private State state;
	private String username;
	private String mobile;
	private String email;
	private String course;
	private String gender;
	private String password;
	private String isDefault="No";

	public Addnewuser() {
	}

	public Addnewuser(String isDefault) {
		this.isDefault = isDefault;
	}

	public Addnewuser(State state, String username, String mobile, String email, String course, String gender,
			String password, String isDefault) {
		this.state = state;
		this.username = username;
		this.mobile = mobile;
		this.email = email;
		this.course = course;
		this.gender = gender;
		this.password = password;
		this.isDefault = isDefault;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER,cascade = CascadeType.ALL)
	@JoinColumn(name = "state_id")
	public State getState() {
		return this.state;
	}

	public void setState(State state) {
		this.state = state;
	}

	@Column(name = "username", length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "mobile", length = 45)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "course", length = 45)
	public String getCourse() {
		return this.course;
	}

	public void setCourse(String course) {
		this.course = course;
	}

	@Column(name = "gender", length = 45)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
	@ColumnDefault(value="'No'")
	@Column(name = "isDefault", nullable = false, length = 45)
	public String getIsDefault() {
		return this.isDefault;
	}

	public void setIsDefault(String isDefault) {
		this.isDefault = isDefault;
	}

}
