package com.jbk.hibernate;
// Generated 3 May, 2020 10:18:44 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Downloads generated by hbm2java
 */
@Entity
@Table(name = "downloads", catalog = "mvcwithhibernate")
public class Downloads implements java.io.Serializable {

	private Integer sr;
	private String version;
	private String name;
	private String vendor;
	private String bit;
	private String bigbit;
	private String common;
	private String officialSource;

	public Downloads() {
	}

	public Downloads(String name, String vendor, String officialSource) {
		this.name = name;
		this.vendor = vendor;
		this.officialSource = officialSource;
	}

	public Downloads(String name, String vendor, String bit, String bigbit, String common, String officialSource) {
		this.name = name;
		this.vendor = vendor;
		this.bit = bit;
		this.bigbit = bigbit;
		this.common = common;
		this.officialSource = officialSource;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "sr", unique = true, nullable = false)
	public Integer getSr() {
		return this.sr;
	}

	public void setSr(Integer sr) {
		this.sr = sr;
	}

	
	@Column(name = "version", nullable = false, length = 45)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "vendor", nullable = false, length = 45)
	public String getVendor() {
		return this.vendor;
	}

	public void setVendor(String vendor) {
		this.vendor = vendor;
	}

	@Column(name = "bit", length = 100)
	public String getBit() {
		return this.bit;
	}

	public void setBit(String bit) {
		this.bit = bit;
	}

	@Column(name = "bigbit", length = 100)
	public String getBigbit() {
		return this.bigbit;
	}

	public void setBigbit(String bigbit) {
		this.bigbit = bigbit;
	}

	@Column(name = "common", length = 100)
	public String getCommon() {
		return this.common;
	}

	public void setCommon(String common) {
		this.common = common;
	}

	@Column(name = "official source", nullable = false, length = 100)
	public String getOfficialSource() {
		return this.officialSource;
	}

	public void setOfficialSource(String officialSource) {
		this.officialSource = officialSource;
	}

	@Override
	public String toString() {
		return "Downloads [sr=" + sr + ", version=" + version + ", name=" + name + ", vendor=" + vendor + ", bit=" + bit
				+ ", bigbit=" + bigbit + ", common=" + common + ", officialSource=" + officialSource + "]";
	}

}
