package com.jbk.hibernate;
// Generated 3 May, 2020 5:57:53 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Links generated by hbm2java
 */
@Entity
@Table(name = "links", catalog = "mvcwithhibernate")
public class Links implements java.io.Serializable {

	private Integer sr;
	private String content;
	private String click;

	public Links() {
	}

	public Links(String content, String click) {
		this.content = content;
		this.click = click;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Sr", unique = true, nullable = false)
	public Integer getSr() {
		return this.sr;
	}

	public void setSr(Integer sr) {
		this.sr = sr;
	}

	@Column(name = "content", nullable = false, length = 45)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "click", nullable = false, length = 100)
	public String getClick() {
		return this.click;
	}

	public void setClick(String click) {
		this.click = click;
	}

	@Override
	public String toString() {
		return "Links [sr=" + sr + ", content=" + content + ", click=" + click + "]";
	}
	

}
