package com.jbk.hibernate;
// Generated 30 Apr, 2020 9:40:09 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Statemaster generated by hbm2java
 */
@Entity
@Table(name = "statemaster", catalog = "mvcwithhibernate")
public class Statemaster implements java.io.Serializable {

	private Integer sid;
	private String name;

	public Statemaster() {
	}

	public Statemaster(String name) {
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "sid", unique = true, nullable = false)
	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
